### ISSUE TITLE
`cmp` command is not implemented

### ISSUE THREAD

**Issue by oSoMoN** [uutils/diffutils#14]
Currently uutils' diffutils only implements the `diff` executable.

But GNU's diffutils also provide `cmp`, `diff3` and `sdiff`.

This issue is a tracker for the implementation of the `cmp` utility.

Documentation: https://www.gnu.org/software/diffutils/manual/html_node/Invoking-cmp.html.

**Comment by radhesh1** [comment]
i have made a separate file cmp.rs

**Comment by radhesh1** [comment]
and implemented a basic cmp with no fuzzing yet

**Comment by radhesh1** [comment]
for cmp testing would be have some dummy files?

**Comment by kov** [comment]
I've submitted an implementation of cmp here https://github.com/uutils/diffutils/pull/88
